### ISSUE TITLE
it seems like that depth can read only with specail tifffile version like 2020.2.16

### ISSUE THREAD

**Issue by linharrrrrt** [vislearn/dsacstar#1]
when using python to read depth information, the dataloader seem like only work with package tifffile==2020.2.16

**Comment by ebrach** [comment]
Hi,
thanks for reporting. For reading depth files, we entirely rely on the skimage package, see 

https://github.com/vislearn/dsacstar/blob/3aa904728c82720da798ee60b71dfdd07e86352d/dataset.py#L144

Therefore, the issue might more be related to skimage, than to DSAC*.

Best,
Eric

**Comment by chudur-budur** [comment]
Here is a conda `environment.yml` file that works with the code out of the box:

```YAML
name: dsacstar
channels:
    - conda-forge
    - pytorch
dependencies:
    - scikit-image=0.16.2
    - pytorch=1.6.0
    - opencv=3.4.2
    - torchvision=0.7.0
    - cudatoolkit=10.2.89
```
